Merging Datasets

In [1]:
import pandas as pd

df = pd.read_csv("temperature.csv")
counts = pd.read_csv("ecocounter_bike_traffic_data.csv")

In [2]:
temperature = df[["DATE", "LATITUDE", "LONGITUDE", "TOBS"]]
temperature = temperature.rename(columns={'DATE': 'Date', 'LATITUDE': 'latitude', 'LONGITUDE': 'longitude', 'TOBS': 'temperature'})
temperature

            Date  latitude  longitude  temperature
0     2023-05-24   38.5349  -121.7761         61.0
1     2023-05-25   38.5349  -121.7761         65.0
2     2023-05-26   38.5349  -121.7761         62.0
3     2023-05-27   38.5349  -121.7761         63.0
4     2023-05-28   38.5349  -121.7761         59.0
...          ...       ...        ...          ...
996   2026-02-17   38.5349  -121.7761         43.0
997   2026-02-18   38.5349  -121.7761         40.0
998   2026-02-19   38.5349  -121.7761         42.0
999   2026-02-20   38.5349  -121.7761         36.0
1000  2026-02-21   38.5349  -121.7761         36.0

[1001 rows x 4 columns]

In [3]:
data = pd.merge(counts, temperature, on='Date', how='left')
data

           Date  Count  latitude  longitude  temperature
0    2024-01-01    307   38.5349  -121.7761         44.0
1    2024-01-02    360   38.5349  -121.7761         49.0
2    2024-01-03    475   38.5349  -121.7761         46.0
3    2024-01-04    580   38.5349  -121.7761         39.0
4    2024-01-05    646   38.5349  -121.7761         45.0
..          ...    ...       ...        ...          ...
726  2025-12-27    231   38.5349  -121.7761         44.0
727  2025-12-28    221   38.5349  -121.7761         41.0
728  2025-12-29    295   38.5349  -121.7761         35.0
729  2025-12-30    238   38.5349  -121.7761         39.0
730  2025-12-31    131   38.5349  -121.7761         43.0

[731 rows x 5 columns]

In [4]:
data.to_csv("merged_data.csv", index=False)